import { openApiMockClient } from "../../libs/test/client";

const mockData = [
  {
    id: "c686397e4a0f4f11683d",
    title: "React NativeとExpoで始めるモバイルアプリ開発",
    body: "# React NativeとExpoで始めるモバイルアプリ開発\n\n...",
    rendered_body: "<h1>React NativeとExpoで始めるモバイルアプリ開発</h1>",
    url: "https://qiita.com/qiita/items/c686397e4a0f4f11683d",
    private: false,
    coediting: false,
    slide: false,
    user: {
      id: "qiita",
      name: "Qiita 太郎",
      description: "Hello, world.",
      profile_image_url: "https://example.com/avatar.png",
      website_url: "https://qiita.com",
      organization: "Qiita Inc.",
      location: "Tokyo, Japan",
      github_login_name: "qiitan",
      twitter_screen_name: "qiita",
      facebook_id: "qiita",
      linkedin_id: "qiita",
      permanent_id: 1,
      items_count: 300,
      followees_count: 100,
      followers_count: 200,
      team_only: false,
    },
    tags: [
      { name: "React Native", versions: [] },
      { name: "Expo", versions: [] },
      { name: "TypeScript", versions: [] },
    ],
    group: null,
    team_membership: null,
    organization_url_name: null,
    created_at: "2024-01-15T09:00:00+09:00",
    updated_at: "2024-01-15T09:00:00+09:00",
    comments_count: 5,
    likes_count: 10,
    reactions_count: 3,
    stocks_count: 8,
    page_views_count: 100,
  },
  {
    id: "d797508f5b1f5f22794e",
    title: "NativeWindでReact Nativeのスタイリングを効率化",
    body: "# NativeWindでReact Nativeのスタイリングを効率化\n\n...",
    rendered_body: "<h1>NativeWindでReact Nativeのスタイリングを効率化</h1>",
    url: "https://qiita.com/developer/items/d797508f5b1f5f22794e",
    private: false,
    coediting: false,
    slide: false,
    user: {
      id: "developer",
      name: "Developer Taro",
      description: "Web Developer",
      profile_image_url: "https://example.com/avatar2.png",
      website_url: "https://developer.example.com",
      organization: "Tech Corp",
      location: "Osaka, Japan",
      github_login_name: "devtaro",
      twitter_screen_name: "devtaro",
      facebook_id: null,
      linkedin_id: null,
      permanent_id: 2,
      items_count: 50,
      followees_count: 30,
      followers_count: 80,
      team_only: false,
    },
    tags: [
      { name: "NativeWind", versions: [] },
      { name: "TailwindCSS", versions: [] },
      { name: "React Native", versions: [] },
    ],
    group: null,
    team_membership: null,
    organization_url_name: null,
    created_at: "2024-01-10T14:30:00+09:00",
    updated_at: "2024-01-10T14:30:00+09:00",
    comments_count: 2,
    likes_count: 15,
    reactions_count: 5,
    stocks_count: 12,
    page_views_count: 200,
  },
];

const success = openApiMockClient.get("/items", ({ response }) => {
  return response(200).json(mockData);
});

export const ArticleMocks = {
  Success: [success],
};
