name: Typecheck
on:
  pull_request:
    types: [opened, synchronize, reopened]
    paths:
      - 'graphql/**'
      - '!.github/workflows/**'
      - '.github/workflows/typecheck.yaml'
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  run-ci:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: graphql
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          sparse-checkout: |
            graphql
      - uses: pnpm/action-setup@a7487c7e89a18df4991f7f222e4898a00d66ddda # v4.1.0
        with:
          package_json_file: graphql/package.json
      - uses: actions/setup-node@a0853c24544627f65ddf259abe73b1d18a591444 # v5.0.0
        with:
          node-version-file: graphql/.node-version
          cache: 'pnpm'
          cache-dependency-path: 'graphql/**/pnpm-lock.yaml'
      - name: Install Dependencies
        run: pnpm install --frozen-lockfile
      - name: Typecheck
        run: |
          pnpm db:generate
          pnpm typecheck
        env:
          DATABASE_URL: "file:./dev.db"
