name: Test
on:
  pull_request:
    types: [opened, synchronize, reopened]
    paths:
      - 'mobile/**'
      - '!.github/workflows/**'
      - '.github/workflows/mobile_test.yaml'
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  run-ci:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: mobile
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          sparse-checkout: |
            mobile
      - uses: pnpm/action-setup@a7487c7e89a18df4991f7f222e4898a00d66ddda # v4.1.0
        with:
          package_json_file: mobile/package.json
      - uses: actions/setup-node@a0853c24544627f65ddf259abe73b1d18a591444 # v5.0.0
        with:
          node-version-file: mobile/.node-version
          cache: 'pnpm'
          cache-dependency-path: 'mobile/**/pnpm-lock.yaml'
      - name: Install Dependencies
        run: pnpm install --frozen-lockfile
      - name: Test
        run: pnpm test
