name: VRT
on:
  pull_request:
    types: [opened, synchronize, reopened]
    paths:
      - 'mobile/**'
      - '!.github/workflows/**'
      - '.github/workflows/mobile_vrt.yml'

jobs:
  vrt:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
      pull-requests: write
    defaults:
      run:
        working-directory: mobile
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          sparse-checkout: |
            mobile
      - uses: pnpm/action-setup@a7487c7e89a18df4991f7f222e4898a00d66ddda # v4.1.0
        with:
          package_json_file: mobile/package.json
      - uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
        with:
          node-version-file: mobile/.node-version
          cache: 'pnpm'
          cache-dependency-path: 'mobile/**/pnpm-lock.yaml'
      - name: Install fonts
        # 日本語が文字化けするためフォントをインストールする
        run: sudo apt install language-pack-ja fontconfig fonts-ipafont
      - name: Install Dependencies
        run: pnpm install --frozen-lockfile
      - name: Storybook VRT
        run: pnpm vrt
      - uses: peter-evans/find-comment@3eae4d37986fb5a8592848f6a574fdf654e61f9e # v3.1.0
        id: find-comment
        if: always()
        with:
          comment-author: github-actions[bot]
          issue-number: ${{ github.event.pull_request.number }}
          body-includes: "VRTが完了しました"
      - name: comments to PR
        uses: peter-evans/create-or-update-comment@71345be0265236311c031f5c7866368bd1eff043 # v4.0.0
        if: success()
        with:
          comment-id: ${{ steps.find-comment.outputs.comment-id }}
          issue-number: ${{ github.event.pull_request.number }}
          body: |
            VRTが完了しました
            差分はありません
          edit-mode: replace
      - name: comments to PR
        uses: peter-evans/create-or-update-comment@71345be0265236311c031f5c7866368bd1eff043 # v4.0.0
        if: failure()
        with:
          comment-id: ${{ steps.find-comment.outputs.comment-id }}
          issue-number: ${{ github.event.pull_request.number }}
          body: |
            VRTが完了しました
            :warning: **VRT に差分があります**
          edit-mode: replace
      - name: Save VRT Report
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
        if: failure()
        with:
          name: report
          path: ./vrt/public/report
