name: VRT Approve
on:
  workflow_dispatch:

jobs:
  approve:
    runs-on: ubuntu-latest
    if: github.ref_name != 'main'
    permissions:
      id-token: write
      contents: write
      pull-requests: write
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - uses: pnpm/action-setup@a7487c7e89a18df4991f7f222e4898a00d66ddda # v4.1.0
        with:
          package_json_file: package.json
      - uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
        with:
          node-version-file: .node-version
          cache: 'pnpm'
          cache-dependency-path: '**/pnpm-lock.yaml'
      - name: Install fonts
        # 日本語が文字化けするためフォントをインストールする
        run: sudo apt install language-pack-ja fontconfig fonts-ipafont
      - name: Install Dependencies
        run: pnpm install --frozen-lockfile
      - name: Storybook VRT
        run: pnpm vrt:approve
      - name: Configure Git
        run: |
          git config user.name ${{ github.actor }}
          git config user.email ${{ github.actor }}@users.noreply.github.com
      - name: Update VRT Approve
        run: |
          git status
          git diff
          git add vrt/public/report/expected
          git commit -m "VRT Approve"
          git push origin ${{ github.head_ref }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
